import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { AccessPerformanceAllocationService } from '../src/domain.mjs';
import { AtomicStore } from '../src/store.mjs';

class MemoryStore { constructor() { this.database = { accessPerformanceAllocationReviews: [] }; this.writes = 0; } read() { return structuredClone(this.database); } write(data) { this.database = structuredClone(data); this.writes += 1; } }
const owner = { id: 'owner-844', role: 'evidence_owner' };
const input = { supplierId: 'SUP-844', evidenceReference: 'EVD-844', allocationReference: 'ALC-844-ACCESS-01', allocationScope: 'access_capacity_allocation' };
const chain = [{ action: 'assessAllocation', role: 'allocation_assessment_analyst' }, { action: 'verifyCapacity', role: 'allocation_capacity_verifier' }, { action: 'validateAssignment', role: 'allocation_assignment_validator' }, { action: 'authorizeAllocation', role: 'allocation_authority' }, { action: 'releaseAllocation', role: 'allocation_registrar' }];

describe('AccessPerformanceAllocationService', () => {
  it('records the complete independently controlled allocation lifecycle', () => { const store = new MemoryStore(); const service = new AccessPerformanceAllocationService(store); let record = service.submit(input, owner, 'request-submit-844'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `request-${step.action}-844`); expect(record.status).toBe('allocation_released'); expect(record.events.map((event) => event.type)).toContain('allocation_released'); expect(store.writes).toBe(6); });
  it('rejects invalid allocation input and invalid role or state without mutation', () => { const store = new MemoryStore(); const service = new AccessPerformanceAllocationService(store); expect(() => service.submit({ ...input, allocationScope: 'other' }, owner, 'request-invalid-844')).toThrow('allocation scope is invalid'); const record = service.submit(input, owner, 'request-state-844'); expect(() => service.transition(record.id, 'assessAllocation', { note: 'attempt' }, owner, 'request-role-844')).toThrow('role allocation_assessment_analyst is required'); expect(() => service.transition(record.id, 'validateAssignment', { note: 'order' }, { id: 'validator', role: 'allocation_assignment_validator' }, 'request-order-844')).toThrow('access-performance allocation review must be capacity_verified'); expect(store.writes).toBe(1); });
  it('rejects duplicate requests, missing records, and terminal transitions', () => { const store = new MemoryStore(); const service = new AccessPerformanceAllocationService(store); let record = service.submit(input, owner, 'request-repeat-844'); expect(() => service.transition(record.id, 'assessAllocation', { note: 'repeat' }, { id: 'assessor', role: 'allocation_assessment_analyst' }, 'request-repeat-844')).toThrow('request identifier was already used'); expect(() => service.get('missing-844')).toThrow('access-performance allocation review was not found'); for (const step of chain) record = service.transition(record.id, step.action, { note: step.action }, { id: step.role, role: step.role }, `terminal-${step.action}-844`); expect(() => service.transition(record.id, 'releaseAllocation', { note: 'retry' }, { id: 'registrar', role: 'allocation_registrar' }, 'retry-release-844')).toThrow('access-performance allocation review must be allocation_authorized'); });
  it('recovers an absent allocation data file', () => { const directory = mkdtempSync(join(tmpdir(), 'access-performance-allocation-')); try { const store = new AtomicStore(join(directory, 'data', 'access-performance-allocation-reviews.json')); expect(store.read()).toEqual({ accessPerformanceAllocationReviews: [] }); } finally { rmSync(directory, { recursive: true, force: true }); } });
});
